@startuml
@startuml
title Taymindis_fcgi-function Component Diagram

package "Taymindis_fcgi-function" {
    [README.md]
    [ffunc.c]
    [ffunc.h]
    [CMakeLists.txt]
    [LICENSE]
    [images]
    [DockerExample]
    [examples]
    [Testing]
}

cloud "FastCGI" {
}

database "Nginix FastCGI module" {
}

cloud "Logging Libraries" {
    [spdlog]
    [g3log]
    [mini-async-log]
}

[Taymindis_fcgi-function] --> [Nginix FastCGI module]
[Taymindis_fcgi-function] --> [FastCGI]
[Taymindis_fcgi-function] --> [Logging Libraries]

@enduml
@enduml