@startuml
actor User

node "Client Environment" {
    package "ActiveX.NET.Server" {
        [Program.cs] --> [ActiveXServerContext.cs]
        [ActiveXServerContext.cs] --> [ActiveXServers.cs]
        [ActiveXServers.cs] --> [DefaultActiveXFactory]
        [Program.cs] --down-> "App.config"
    }
    
    package "ActiveX.NET.Plugin" {
        [CoClass.cs] --> [SimpleObject]
    }

    package "ActiveX.NET.Common" {
        [ActiveXServerBase.cs] --> [IActiveXServer]
        [ActiveXServerMTABase] --> [ActiveXServerBase.cs]
        [ActiveXServerControlBase] --> [ActiveXServerBase.cs]
        [ActiveXServerAttribute.cs]
    }
}

node "Server Environment" {
    [IActiveXServer] <.. [ActiveXServers]
    [DefaultActiveXFactory] <.. [ActiveXServers]
    [ActiveXServerContext.cs] --> [IActiveXServer]
}

User -> "Client Environment": Starts COM Server
[Program.cs] -> [ActiveXServerContext.cs]: Initialize Server
[ActiveXServerContext.cs] -> [ActiveXServers.cs]: Discover COM Objects
[ActiveXServers.cs] -> [DefaultActiveXFactory]: Create COM Instances
[CoClass.cs] -> [SimpleObject]: Implement COM Object
[SimpleObject] <.. [ActiveXServerBase.cs]: Inherits
[ActiveXServerMTABase] <.. [ActiveXServerBase.cs]: Inherits
[ActiveXServerControlBase] <.. [ActiveXServerBase.cs]: Inherits
[ActiveXServerAttribute.cs] --> [ActiveXServers]: Register COM Object

@enduml