```plantuml
@startuml calmato_gran-book

package "Gran Book Application" {
    
    component "Web Admin Panel" {
        [Admin Interface] --> [API Gateway]
        [Vuex Store] --> [Admin Interface]
        [Vue.js Components] --> [Admin Interface]
        [Nuxt.js Plugins] --> [Admin Interface]
    }

    component "Backend" {
        [API Gateway] --> [Auth API]
        [API Gateway] --> [User API]
        [API Gateway] --> [Book API]
        [API Gateway] --> [Chat API]
        [gRPC Services] --> [Auth API]
        [gRPC Services] --> [User API]
        [gRPC Services] --> [Book API]
        [gRPC Services] --> [Chat API]
        [Database] --> [Auth API]
        [Database] --> [User API]
        [Database] --> [Book API]
        [Database] --> [Chat API]
    }

    component "External Services" {
        [Firebase] --> [Backend]
        [Image Storage] --> [Backend]
    }

    [API Gateway] --> [RESTful APIs]
    [RESTful APIs] --> [Backend]

    [Web Admin Panel] --> [Backend]
    [Backend] --> [External Services]

}

@enduml
```