```plantuml
@startuml chsakell_planet-scale-azure

package "Planet-Scale Online Store Application" {

    [Angular App] --> [ASP.NET Core Web API]

    [ASP.NET Core Web API] --> [Azure Traffic Manager]
    [ASP.NET Core Web API] --> [Azure Redis Cache]
    [ASP.NET Core Web API] --> [Azure Service Bus]
    [ASP.NET Core Web API] --> [Azure Cosmos DB]
    [ASP.NET Core Web API] --> [Azure SQL Server]
    [ASP.NET Core Web API] --> [Azure Search]

    [Azure Traffic Manager] --> [Azure CDN]
    [Azure Traffic Manager] --> "Multi-region" [ASP.NET Core Web API]

    [Azure Service Bus] --> [WebJob]

    [Azure SQL Server] --> "Geo-replication" [Azure SQL Server]
    [Azure Cosmos DB] --> "Geo-replication" [Azure Cosmos DB]

    cloud "Azure" {
        [Azure Traffic Manager]
        [Azure CDN]
        [Azure Redis Cache]
        [Azure Service Bus]
        [Azure Cosmos DB]
        [Azure SQL Server]
        [Azure Search]
    }

    node "WebJobs" {
        [WebJob]
    }

    package "Client App" {
        [Angular App]
    }

    package "Server Side" {
        [ASP.NET Core Web API]
    }
}

@enduml
```