```plantuml
@startuml danielfm_prometheus-for-developers

actor Developer

Developer -> NodeJS_Application: Send HTTP Request
NodeJS_Application -> NodeJS_Application: Handle Request
NodeJS_Application -> Prometheus_Client: Collect Metrics
Prometheus_Client -> NodeJS_Application: Return Metrics
NodeJS_Application -> Developer: Send Response

Prometheus -> NodeJS_Application: Scrape Metrics
NodeJS_Application -> Prometheus: Provide Metrics

Prometheus -> Alertmanager: Send Alerts
Alertmanager -> Alertmanager: Process Alerts

Grafana -> Prometheus: Query Metrics
Prometheus -> Grafana: Return Metrics
Grafana -> Developer: Visualize Metrics

@enduml
```