```plantuml
@startuml laziestcoder_Budget_App_JS

    actor User

    User -> UIController: inputIncomeExpense(desc, value)
    activate UIController

    UIController -> budgetController: addItem(type, desc, value)
    activate budgetController

    budgetController -> budgetController: calculateBudget()
    budgetController -> budgetController: calculatePercentages()

    budgetController -> UIController: getBudgetData()
    deactivate budgetController
    activate UIController

    UIController -> UIController: updateUI(budgetData)

    UIController -> User: displayUpdatedBudget()

    deactivate UIController

@enduml
```