```plantuml
@startuml lkmSasanga_fas-web-app

package "Web Application" {
    [App] -[#blue]-> [Search and Analysis]
    [App] -[#blue]-> [Dashboard]
    [App] -[#blue]-> [User Authentication]
    [App] -[#blue]-> [Data Visualization]
    [App] -[#blue]-> [Reusable UI Components]
    
    [Search and Analysis] --> [InputControl]
    [Dashboard] --> [Charts]
    [User Authentication] --> [Login]
    [User Authentication] --> [Signup]
    [Data Visualization] --> [Charts]
    [Reusable UI Components] --> [Backdrop]
    [Reusable UI Components] --> [Spinner]
    [Reusable UI Components] --> [Cards]
    [Reusable UI Components] --> [DonetChart]
    [Reusable UI Components] --> [ProgressBar]
    [Reusable UI Components] --> [Navigation]
}

package "Backend API" {
    [Sentiment Analysis API] --> [Sentiment Data]
}

package "Deployment" {
    [Firebase Hosting]
}

[App] --> [Sentiment Analysis API] : "Fetch Data" 
[Sentiment Analysis API] --> [Firebase Hosting] : "Deploy"

[InputControl] ..> [RequestData] : "Fetch Data"
[RequestData] --> [Sentiment Analysis API] : "API Call"

@enduml
```