```plantuml
@startuml lkravi_kube8aws

package "AWS Cloud" {
    component "VPC" {
        component "Public Subnet" {
            [Bastion Host]
        }
        component "Private Subnet" {
            [Master Node 1]
            [Master Node 2]
            [Master Node 3]
            [Worker Node 1]
            [Worker Node 2]
            [Worker Node 3]
        }
    }

    [Network Load Balancer] --> [Bastion Host]
    [Network Load Balancer] --> [Master Node 1]
    [Network Load Balancer] --> [Master Node 2]
    [Network Load Balancer] --> [Master Node 3]

    [Bastion Host] -up-> [Ansible Control Node]

    [Bastion Host] --> [Master Node 1]
    [Bastion Host] --> [Master Node 2]
    [Bastion Host] --> [Master Node 3]
    [Bastion Host] --> [Worker Node 1]
    [Bastion Host] --> [Worker Node 2]
    [Bastion Host] --> [Worker Node 3]
}

package "Terraform Configuration" {
    [vpc.tf] --> [VPC]
    [servers.tf] --> [Bastion Host]
    [servers.tf] --> [Master Node 1]
    [servers.tf] --> [Master Node 2]
    [servers.tf] --> [Master Node 3]
    [servers.tf] --> [Worker Node 1]
    [servers.tf] --> [Worker Node 2]
    [servers.tf] --> [Worker Node 3]
    [load_balance.tf] --> [Network Load Balancer]
    [security.tf] --> [Bastion Host]
    [security.tf] --> [Master Node 1]
    [security.tf] --> [Master Node 2]
    [security.tf] --> [Master Node 3]
    [security.tf] --> [Worker Node 1]
    [security.tf] --> [Worker Node 2]
    [security.tf] --> [Worker Node 3]
    [ansible_helper.tf] -down-> [Ansible Control Node]
}

@enduml
```