```plantuml
@startuml wso2_chef-apim

package "WSO2 API Manager 2.2.0 Chef Cookbook" {
    
    component "Automated Deployment" as AD
    component "Distributed Setup Support" as DSS
    component "Configuration Management" as CM
    component "Java Installation" as JI
    component "MySQL Database Setup" as MDBS
    component "Service Management" as SM
    component "Clustering Configuration" as CC

    AD --> DSS
    AD --> CM
    AD --> JI
    AD --> MDBS
    AD --> SM
    AD --> CC

    component "attributes/default.rb" as Attributes
    component "recipes/default.rb" as MainRecipe
    component "recipes/wso2_apim_installation.rb" as WSO2Install
    component "recipes/apply_template.rb" as ApplyTemplate
    component "templates/*" as Templates

    CM --> Attributes
    CM --> ApplyTemplate
    CM --> Templates
    JI --> MainRecipe
    JI --> Attributes
    DSS --> WSO2Install
    DSS --> Templates
    MDBS --> Attributes
    SM --> MainRecipe
    CC --> Attributes
}

@enduml
```