@startuml
@startuml
title Zswag Repository Component Diagram

package "zswagcl" {
  [OAClient]
}

database "zswag" {
  [OAClient]
  [OAServer]
}

cloud "pyzswagcl" {
  [C++-based OpenAPI parsing/request functionality]
}

database "httpcl" {
  [HTTP request configuration]
  [OS secret storage abilities]
}

[zswagcl] --> [OAClient]
[zswag] --> [OAClient]
[zswag] --> [OAServer]
[pyzswagcl] --> [C++-based OpenAPI parsing/request functionality]
[httpcl] --> [HTTP request configuration]
[httpcl] --> [OS secret storage abilities]

@enduml
@enduml