@startuml
package "cordon-thiago/airflow-spark" {
  component "Apache Spark" as spark
  component "Apache Airflow" as airflow
  component "Kubernetes" as k8s
  component "PostgreSQL" as postgres
  component "R Language" as rlang
  component "Java Interoperability" as java
  component "Docker" as docker

  database "Data Lake" as datalake
  database "Data Warehouse" as datawarehouse

  airflow -down-> spark : "Orchestrates Spark Jobs"
  spark -down-> datalake : "Reads/Writes"
  spark -down-> datawarehouse : "Reads/Writes"
  rlang -right-> spark : "Uses SparkR"
  java -right-> spark : "Interoperates with Java"
  airflow -up-> postgres : "Manages Jobs"
  postgres -right-> spark : "Reads/Writes"
  docker -left-> spark : "Containerization"
  k8s -left-> docker : "Orchestration"
}

@enduml