@startuml
!define MySQL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/mysql.puml
!define NodeJS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/nodejs.puml
!define Docker https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/docker.puml
!define Redis https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/redis.puml
!define NGINX https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/nginx.puml
!define S3 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.2.0/devicons/amazonwebservices.puml

skinparam linetype ortho

package "Bunny Code Platform" {
  [Node.js Application] <<NodeJS>> 
  [Docker Container] <<Docker>> 
  [Nginx Reverse Proxy] <<NGINX>>
  [MySQL Database] <<MySQL>>
  [Redis Cache] <<Redis>>
  [S3 Storage] <<S3>>

  [Node.js Application] -right-> [MySQL Database] : API Requests
  [Node.js Application] -up-> [Redis Cache] : Caching
  [Node.js Application] -down-> [Docker Container] : Sandbox Execution
  [Node.js Application] -left-> [S3 Storage] : File Storage
  [Node.js Application] <-down- [Nginx Reverse Proxy] : Routing
  [Docker Container] -down-> [Node.js Application] : Code Execution
}

@enduml