@startuml
skinparam componentStyle rectangle

package "FIFArm Application" {
    [Web Browser] -right-> [Web Interface]
    [Web Interface] --> [Thymeleaf Templates]
    [Web Interface] --> [Spring MVC Controllers]

    package "Spring Boot Application" {
        [Spring MVC Controllers] -right-> [JsonController]
        [JsonController] --> [RESTful API]
        [Spring MVC Controllers] --> [IndexController]
        [Spring MVC Controllers] --> [PathController]

        [RESTful API] --> [MongoService]
        [RESTful API] --> [HttpRequestService]
        [MongoService] --> [MongoDB]
        [HttpRequestService] --> [EA Sports FUT API]
        
        [Scheduler] -left-> [Scheduled Data Refresh]

        [LogService] -down-> [Logback]
    }
}

package "Configuration & Assets" {
    [application.yml] --> [Spring Boot Application]
    [logback.xml] --> [Logback]
    [templates] --> [Thymeleaf Templates]
    [static] -left-> [Web Interface]
}

[Web Browser] --> [Client Device]

@enduml