@startuml
package "Linux Commands Tutorial Repository" {
  [README.md] --> [Individual .md Files]
  [README.md] --> [_config.yml]

  package "Individual .md Files" {
    [filtercommands.md]
    [filepermissions.md]
    [signalsinlinux.md]
    [topcommand.md]
    [useradmin.md]
    [groupadmin.md]
    [Basic-commands.md]
    [ls.md]
    [grep.md]
    [findcommand.md]
    [links.md]
    [managingprocess.md]
    [vi.md]
    [changing-ownership-and-group.md]
  }

  [README.md] --> [filtercommands.md]
  [README.md] --> [filepermissions.md]
  [README.md] --> [signalsinlinux.md]
  [README.md] --> [topcommand.md]
  [README.md] --> [useradmin.md]
  [README.md] --> [groupadmin.md]
  [README.md] --> [Basic-commands.md]
  [README.md] --> [ls.md]
  [README.md] --> [grep.md]
  [README.md] --> [findcommand.md]
  [README.md] --> [links.md]
  [README.md] --> [managingprocess.md]
  [README.md] --> [vi.md]
  [README.md] --> [changing-ownership-and-group.md]
}
@enduml