@startuml

package "NLP4L Library" {

  package "Core" {
    [Schema] 
    [Field]
    [FieldType]
    [Document]
    [SchemaLoader]
  }

  package "Indexing & Searching" {
    [IWriter]
    [IReader]
    [RawReader]
    [ISearcher]
  }

  package "Text Analysis" {
    [Analyzer]
    [AnalyzerBuilder]
    [Token]
    [BrownCorpusAnalyzer]
    [TermDocs]
    [Terms]
    [Doc]
    [PosAndOffset]
  }

  package "NLP Algorithms" {
    package "HMM" {
      [HmmModel]
      [HmmTagger]
      [HmmTokenizer]
      [AbstractNode]
      [Node]
      [HmmTracer]
      [SimpleFST]
      [HmmModelIndexer]
    }
    package "Collocational Analysis" {
      [CollocationalAnalysisModel]
      [CollocationalAnalysisModelIndexer]
      [CollocationalAnalysisModelSchema]
    }
  }

  package "Corpus Handling" {
    [Corpora]
  }

  package "REPL" {
    [NLP4LILoop]
    [NLP4LMainGenericRunner]
    [NLP4L]
    [ZeppelinVisualizer]
  }

  package "Synonym Management" {
    [SynonymRecords]
    [SynonymRecordsUnifier]
    [SynonymCommon]
    [UnifySynonymRecordsProcessor]
  }

  package "Feature Selection & Extraction" {
    [FeatureSelector]
    [TermsExtractor]
    [TermsExtractionProcessor]
  }

  package "Transliteration" {
    [LoanWordsExtractor]
    [TransliterationModel]
  }

  package "FST Support" {
    [SimpleFST]
  }
}

@enduml