```plantuml
@startuml 23fa-cpsc490_canyough

package "Twitter Recommendation System" {
    [Product Mixer] --> [Cr-Mixer]
    [Product Mixer] --> [Follow Recommendations Service]
    [Product Mixer] --> [Home Mixer]

    package "Components" {
        [Candidate Sources]
        [Feature Hydrators]
        [Filters]
        [Gates]
        [Scorers]
        [Transformers]
        [Cursors]
    }

    [Product Mixer] --> [Components]
    [Cr-Mixer] --> [Components]
    [Follow Recommendations Service] --> [Components]
    [Home Mixer] --> [Components]

    package "Data Sources" {
        [User Signal Service]
        [Real Graph]
        [Earlybird]
        [TweetyPie]
        [Manhattan]
        [Memcached]
        [Strato]
    }

    [Candidate Sources] --> [Data Sources]
    [Feature Hydrators] --> [Data Sources]

    package "Technologies" {
        [gRPC]
        [Thrift]
        [Finagle]
        [Storehaus]
        [Stitch]
        [Protocol Buffers]
    }

    [Twitter Recommendation System] --> [Technologies]

    package "Navi Serving Server" {
        [Navi Serving Server]
        [TensorFlow]
        [ONNX Runtime]
        [Pytorch]
    }

    [Navi Serving Server] --> [Product Mixer]
}

@enduml
```