```plantuml
@startuml avarghesein_ActiveX.NET

actor Client
participant "ActiveX.NET.Server" as Server
participant "ActiveXServers" as Servers
participant "MEF" as MEF
participant "IActiveXServer" as IActiveXServer
participant "ActiveX.NET.Plugin" as Plugin
participant "ActiveXServerContext" as ServerContext

Client -> Server: start
Server -> ServerContext: Initialize
ServerContext -> Server: Load App.config
Server -> MEF: Discover Plugins
MEF -> Plugin: Load CoClass
MEF -> Servers: Exported IActiveXServer
Servers -> IActiveXServer: Create Instance
IActiveXServer -> Plugin: Initialize CoClass

Client -> Server: Request COM Object
Server -> Servers: Get IActiveXServer Instance
Servers -> IActiveXServer: LockActiveXServer
IActiveXServer -> Plugin: Execute Logic
Servers -> IActiveXServer: UnLockActiveXServer

Client -> Server: Stop
Server -> ServerContext: Uninitialize
ServerContext -> Servers: Unregister COM Objects
Server -> MEF: Release Plugins

@enduml
```