```plantuml
@startuml ev2900_OpenSearch_Dashboard_Nginx_Proxy

package "AWS Cloud" {
    [Public Subnet] -down-> [Nginx Proxy Server]
    [Private Subnet] -down-> [OpenSearch Domain]
    
    [Nginx Proxy Server] -- [OpenSearch Domain]
    
    [Public Subnet] -right-> [Internet Gateway]
    [Nginx Proxy Server] -right-> [Internet Gateway]
    
    [Internet Gateway] -right-> [Elastic IP]
}

package "Infrastructure as Code" {
    [CloudFormation Template]
    [Nginx Configuration File]
    
    [CloudFormation Template] --> [VPC and Subnets]
    [CloudFormation Template] --> [Internet Gateway]
    [CloudFormation Template] --> [Security Groups]
    [CloudFormation Template] --> [IAM Role and Instance Profile]
    [CloudFormation Template] --> [EC2 Instance]
    [CloudFormation Template] --> [Elastic IP]
    [CloudFormation Template] --> [Route Table]
    
    [Nginx Configuration File] --> [Nginx Proxy Server]
}

package "DevOps" {
    [GitHub Actions]
    [S3 Bucket]
    
    [GitHub Actions] --> [S3 Bucket] : Upload opensearch_nginx.yaml
}

@enduml
```