```plantuml
@startuml NLP4L_attic-nlp4l

package "NLP4L" {
    
    [IWriter] --> [Lucene Index]
    [IReader] --> [Lucene Index]
    [RawReader] --> [Lucene Index]
    [ISearcher] --> [Lucene Index]

    [Schema] --> [Field]
    [Field] --> [FieldType]
    [Document] --> [Field]

    [Analyzer] --> [Token]
    [AnalyzerBuilder] --> [Analyzer]
    [BrownCorpusAnalyzer] --> [Analyzer]

    [HmmModel] --> [HmmTagger]
    [HmmTagger] --> [HmmTokenizer]
    [HmmTokenizer] --> [Node]
    [SimpleFST] --> [HmmModelIndexer]

    [CollocationalAnalysisModel] --> [CollocationalAnalysisModelIndexer]

    [Corpora] --> [NLP4LILoop]
    [NLP4LILoop] --> [NLP4LMainGenericRunner]
    [NLP4LMainGenericRunner] --> [ZeppelinVisualizer]

    [SynonymRecords] --> [SynonymRecordsUnifier]
    [SynonymRecordsUnifier] --> [SynonymCommon]

    [FeatureSelector] --> [TermsExtractor]
    [TermsExtractor] --> [TermsExtractionProcessor]

    [LoanWordsExtractor] --> [TransliterationModel]

    [SimpleFST] --> [Lucene Index]

}

@enduml
```