@startuml
@startuml

package "TinkerWorks_HomeSensorHub" {
  [homesensorhub.py]
  [kubepods.yaml]
  [run.sh]
  [sensor_types.py]
  [README.md]

  package "Sensors" {
    [MotionSensor]
    [LightSensor]
    [BoschBME]
  }

  package "MQTT Communication" {
    [MQTTSender]
    [MQTTSubscriber]
  }

  package "Testing" {
    [SensorTestFiles]
  }

  package "Asynchronous and Polled Sensors" {
    [AsyncSensors]
    [PolledSensors]
  }
}

[homesensorhub.py] -down-> [sensor_types.py]
[homesensorhub.py] -down-> [MQTT Communication]
[homesensorhub.py] -down-> [Sensors]
[homesensorhub.py] -down-> [Testing]
[homesensorhub.py] -down-> [Asynchronous and Polled Sensors]

[SensorTestFiles] -down-> [Sensors]

[sensor_types.py] -down-> [Sensors]

[MQTT Communication] -down-> [MQTTSender]
[MQTT Communication] -down-> [MQTTSubscriber]

[Asynchronous and Polled Sensors] -down-> [AsyncSensors]
[Asynchronous and Polled Sensors] -down-> [PolledSensors]

@enduml
@enduml