@startuml
skinparam rectangle {
  BackgroundColor #EEEBDC
  ArrowColor #222222
  BorderColor #666666
}

rectangle "Data Ingestion" {
  [Twitter Service] as TS
  [IEX Service] as IEX
  [Manager Service] as MS
}

rectangle "Data Storage" {
  database "MongoDB" as MongoDB
  database "Redis" as Redis
  database "S3" as S3
}

rectangle "Data Processing" {
  [Data Service (Django API)] as DS
}

rectangle "Data Analysis" {
  [SKLearn Model Development] as SMD
  [SKLearn Model Deployment] as SMDE
  [EDA Notebooks] as EDA
}

cloud "External Services" {
  [Twitter API] as TA
  [IEX API] as IEXA
  [AWS Kinesis] as AK
}

TS --> TA : Fetch tweets
IEX --> IEXA : Fetch stock data
MS --> Redis : Manage state & flags
TS --> AK : Stream data
IEX --> AK : Stream data
AK --> MongoDB : Store data
SMD --> S3 : Upload models
SMDE --> S3 : Load models
SMD --> MongoDB : Fetch data
SMDE --> MongoDB : Fetch data & log predictions
DS --> MongoDB : Fetch data
Redis <--> MS : Pub/Sub communication
Redis <--> TS : Pub/Sub communication
Redis <--> IEX : Pub/Sub communication

@enduml