@startuml SafeBreach-Labs_hAFL2
skinparam backgroundColor #eeeeee
skinparam componentStyle rectangle
skinparam ArrowColor red
skinparam ArrowThickness 1

' Outer virtualization layer
rectangle "KVM (L0)" as KVM #eeeeee {
}

' hAFL2 exists at top, interacting with all layers
component "hAFL2" as HAFL2 #bfaaff

' Hyper-V host layer
rectangle "Hyper-V (L1) - Host" as HyperV #ccf2ff {
    
    ' Root partition
    rectangle "Root Partition\nHost OS (L2)" as Root #a3d3f5 {
        component "vmswitch.sys" as VMSWITCH #d4a0f5
        component "CrashMonitoring.sys" as CRASHMON #d4a0f5
    }

    ' Child partition
    rectangle "Child Partition\nGuest VM (L2)" as Guest #7ec6f5 {
        component "harness.sys" as HARNESS #d4a0f5
    }

    HARNESS --> VMSWITCH : interaction
}

' Dotted interaction paths from hAFL2
HAFL2 <..> HARNESS
HAFL2 <..> CRASHMON
HAFL2 <..> VMSWITCH 

@enduml