@startuml shinesolutions_sitechecker-slackbot
skinparam rectangle {
  BackgroundColor #ffffff
  BorderColor black
  Style roundrect
}
left to right direction

actor "Slack User" as user

rectangle "Slack" as slack {
  rectangle "Outgoing Webhook" as webhook
}

rectangle "AWS API Gateway" as apigw

rectangle "Master Lambda" as master {
  rectangle "bot.js" as bot
  rectangle "slack.js" as slackjs
}

package "Worker Lambdas" {
  rectangle "us-east-1" as worker1
  rectangle "eu-west-1" as worker2
  rectangle "ap-southeast-1" as worker3
}

rectangle "Internet" as internet

user --> webhook
webhook --> apigw
apigw --> master

master --> worker1 : distribute URL check
master --> worker2 : distribute URL check
master --> worker3 : distribute URL check

worker1 --> internet : HTTP request
worker2 --> internet : HTTP request
worker3 --> internet : HTTP request

worker1 --> master : return status
worker2 --> master : return status
worker3 --> master : return status

master --> slack : post response
@enduml