@startuml
package "Linux Commands Tutorial Repository" {
  component "README.md" as readme
  component "_config.yml" as config

  package "Tutorials" {
    component "Basic-commands.md" as basic_commands
    component "filtercommands.md" as filter_commands
    component "filepermissions.md" as file_permissions
    component "signalsinlinux.md" as signals
    component "topcommand.md" as top_command
    component "useradmin.md" as user_admin
    component "groupadmin.md" as group_admin
    component "ls.md" as ls_command
    component "grep.md" as grep_command
    component "findcommand.md" as find_command
    component "links.md" as links_command
    component "managingprocess.md" as managing_process
    component "vi.md" as vi_editor
    component "changing-ownership-and-group.md" as changing_ownership
  }

  readme --> basic_commands
  readme --> filter_commands
  readme --> file_permissions
  readme --> signals
  readme --> top_command
  readme --> user_admin
  readme --> group_admin
  readme --> ls_command
  readme --> grep_command
  readme --> find_command
  readme --> links_command
  readme --> managing_process
  readme --> vi_editor
  readme --> changing_ownership
  readme --> config
}
@enduml