import os
import subprocess
from openai import OpenAI
import json
import glob
import shutil
import tempfile
client = OpenAI(api_key="")

def get_plantuml_from_summary(view_details, error_message=None, code=None):
    # The System Prompt now contains all instructions and constraints.
    # It is more direct and uses a numbered list for clarity.
    with open("information.txt", "r", encoding="utf-8") as f:
        knowledge_base = f.read()
    system_prompt = """You are an expert software architect specializing in software architecture views.
Your sole task is to generate a single, complete, and valid architectural view diagram based on the architectural knowledge provided by the user.Use plantuml to represent the architectural notation given in the metadata.
Here is the architectural knowledge which can give you more information on creating views {knowledge_base}.
**Instructions & Constraints:**
1.  **Output Format:** Your response MUST contain ONLY the PlantUML code. Do not include any explanations, apologies, or markdown fences like ```plantuml. Your entire response must start with `@startuml` and end with `@enduml`.
2.  **Adherence to Data:** The diagram must accurately represent the components, connectors, behaviors, and architectural styles described in the user's metadata.
3.  **Architectural Reasoning:** Apply your knowledge of software architecture to create a logical and well-structured diagram that respects the specified concern and scope.
4.  **Completeness:** Ensure all key components and their primary relationships from the metadata are visible in the diagram.
5.  **Clarity:** You are also specializing in creating clear diagrams in a 'box and arrows' style using PlantUML syntax.
6.  **Architectural Notation:** Use appropriate syntax given in the metadata and conventions to represent the architectural elements accurately **please use plantuml as only means of representation**.
"""

    # The User Prompt is now clean and contains ONLY data.
    # Bolding the keys can help the model parse the information.
    user_prompt_parts = ["Here is the complete architectural knowledge for the system:\n"]
    for key, value in view_details.items():
        if value:
            formatted_key = key.replace('_', ' ').title()
            user_prompt_parts.append(f"- **{formatted_key}:** {value}")
    
    user_prompt = "\n".join(user_prompt_parts)

    # The retry instruction is now more prominent and prepended to the system prompt.
    if error_message:
        retry_instruction = f"""**CRITICAL CORRECTION:** A previous attempt failed. You MUST fix the error and generate a valid diagram.
- **Error from previous attempt:** {error_message}
- **Problematic Code to fix:**
```plantuml
{code}
```"""
    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {"role": "system", "content": system_prompt + retry_instruction if error_message else system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.7,
            max_tokens=1024,
            stream=False
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"Error: {e}"


def save_plantuml_code(puml_code, repo_name):
    os.makedirs("zeroShot_gpt_box_knowledge_plantumlcode", exist_ok=True)
    # clean_repo_name = repo_name.replace('/', '_').replace('\\', '_').rstrip('_')
    file_path = os.path.join("zeroShot_gpt_box_knowledge_plantumlcode", f"{repo_name}.puml")
    with open(file_path, "w", encoding="utf-8") as file:
        file.write(puml_code)
    return file_path



def compile_plantuml(repo_name, input_path, output_dir="./zeroShot_gpt_box_knowledge_output_images"):
    os.makedirs(output_dir, exist_ok=True)

    with tempfile.TemporaryDirectory() as temp_dir:
        # Run PlantUML in temporary directory
        result = subprocess.run(
            ["plantuml", "-o", temp_dir, input_path],
            capture_output=True, text=True
        )
        if result.returncode != 0:
            return False, result.stderr
        # Find the generated file (e.g., .png)
        generated_files = glob.glob(os.path.join(temp_dir, "*"))
        if not generated_files:
            return False, "No file generated by PlantUML."

        # Assume one diagram per file — take the first
        generated_file = generated_files[0]
        ext = os.path.splitext(generated_file)[1]
        output_path = os.path.join(output_dir, repo_name + ext)

        shutil.move(generated_file, output_path)

        return True, None



def process_view(repo_name, view_details):

    # Generate and compile PlantUML code with retry mechanism
    max_retries = 3
    attempt = 0
    cnt=0
    error_message = None
    puml_code = None
    
    # Open log file in append mode
    with open("error.log", "a", encoding="utf-8") as log_file:
        while attempt < max_retries:
            puml_code = get_plantuml_from_summary(view_details, error_message=error_message, code=puml_code)
            
            file_path = save_plantuml_code(puml_code, repo_name)
            success, error_message = compile_plantuml(repo_name, file_path)
            
            if success:
                log_file.write(f"Successfully processed repo {repo_name}\n")
                log_file.write(f"PlantUML diagram generated at {file_path}\n")
                break
            else:
                log_file.write(f"Attempt {attempt + 1}: Error in generating PlantUML for {repo_name}\n")
                log_file.write(f"Error message: {error_message}\n")
                attempt += 1
                
        if attempt == max_retries:
            cnt+=1
            log_file.write(f"Failed to generate valid PlantUML for {repo_name} after {max_retries} attempts\n")

    return cnt

def main():
    input_jsonl = "../../experiments/Architectural_knowledge_extraction/generated_summaries.jsonl"
    global_cnt = 0
    total=0
    try:
        with open(input_jsonl, 'r', encoding='utf-8') as f:
            entries = [json.loads(line) for line in f]
    except Exception as e:
        print(f"Error reading JSONL file: {e}")
        return
        
    # A dictionary to hold one-liner explanations for the LLM
    explanations = {
        'repo_name': "The name of the repository",
        'summary': "A high-level overview of the codebase, including its purpose and key features which should be included in architectural view",
        'concern': "The primary architectural viewpoint and focus for this view to be demonstrated ",
        'behavior': "the behavior the view should show that is either static or dynamic according to the corresponding value",
        'granularity_note': "The level of detail to be shown in the view. Lower granularity means more detail, while higher granularity means a broader overview of the system",
        'components_nature': "The type of primary building blocks in the system (e.g., microservices, objects, layers)",
        'connectors_nature': "How components interact (e.g., API calls, message queues, function calls)",
        'qas': "Key quality attributes the architecture must support and should be shown in the view",
        'architecture_scope': "The boundary of the system being modeled (e.g., a single service, the entire application)",
        'architectural_notation': "The specific notation system to be used for the diagram",
        'architectural_styles': "Overarching architectural patterns/styles guiding the design."
    }
    
    # Mapping from your JSONL file keys to the keys used in the explanations dict
    key_mapping = {
        "Repository Name": "repo_name",
        "summary": "summary",
        "Concern": "concern",
        "Behavior": "behavior",
        "Granularity": "granularity_note",
        "Components Nature": "components_nature",
        "Connectors Nature": "connectors_nature",
        "QAs": "qas",
        "Architecture Scope": "architecture_scope",
        "Architectural Notation": "architectural_notation",
        "Architectural Styles": "architectural_styles"
    }

    for entry in entries:
        required_keys = ["Repository Name", "summary", "Concern", "Behavior"]
        # if total>10:
        #     break
        if all(key in entry for key in required_keys):
            clean_repo_name = entry["Repository Name"].replace('/', '_').replace('\\', '_').rstrip('_')
            
            view_details = {}
            # Build the dictionary with explanations
            for json_key, internal_key in key_mapping.items():
                if entry.get(json_key):
                    # Combine the explanation and the value into a single string
                    value = entry[json_key]
                    explanation = explanations[internal_key]
                    view_details[internal_key] = f"({explanation}): {value}"

            global_cnt += process_view(clean_repo_name, view_details)
            total += 1
            print(f"Processed entry: {clean_repo_name}")
        else:
            print(f"Skipping entry due to missing required fields: {entry}")

    print(f"✅ Results saved in results folder. Total failed attempts: {global_cnt}")

if __name__ == "__main__":
    main()
