@startuml hamzatugrul_surl
skinparam rectangle {
  BackgroundColor<<frontend>> #d9e7fd
  BackgroundColor<<backend>> #d8f5d3
  BackgroundColor<<database>> #fff1c9
  BackgroundColor<<cache>> #fddddd
  BackgroundColor<<loadbalancer>> #e6d9fd
  Style roundrect
}
skinparam defaultTextAlignment center

rectangle "User" as User
rectangle "Nginx Load Balancer" <<loadbalancer>> as Nginx

package "Spring Boot Application" <<backend>> {
  rectangle "ShortURLController" as Controller
  rectangle "UrlShortenerService" as Service
  rectangle "ShortUrlRepository" as Repository
  rectangle "KeyGenerator" as KeyGen
  rectangle "SUrlValidator" as Validator
  Controller --> Service
  Service --> Repository
  Service --> KeyGen
  Service --> Validator
}

database "MongoDB" <<database>> as MongoDB
database "Redis Cache" <<cache>> as Redis

User --> Nginx
Nginx --> Controller
Repository --> MongoDB
Repository --> Redis
@enduml