@startuml KuangRD_Autonomous-Driving
skinparam rectangle {
  BackgroundColor<<ros>> #d9e7fd
  BackgroundColor<<control>> #d8f5d3
  BackgroundColor<<perception>> #fddddd
  BackgroundColor<<simulator>> #fff1c9
  Style roundrect
}
skinparam defaultTextAlignment center

package "ROS Nodes" <<ros>> {
  rectangle "Waypoint Loader" as WaypointLoader
  rectangle "Waypoint Updater" as WaypointUpdater
  rectangle "DBW Controller" as DBWController
}

package "Control Systems" <<control>> {
  rectangle "PID Controller" as PID
  rectangle "Steering Control" as Steering
  DBWController --> PID
  PID --> Steering
}

package "Perception" <<perception>> {
  rectangle "Traffic Light Classifier" as TrafficLightClassifier
  rectangle "Image Processor" as ImageProcessor
  WaypointUpdater --> TrafficLightClassifier
  TrafficLightClassifier --> ImageProcessor
}

package "Simulator/Car" <<simulator>> as Simulator
Steering --> Simulator
ImageProcessor --> Simulator

@enduml