```plantuml
@startuml rubenbupe_proyectos-data

!define K8S_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/kubernetes.png
!define GCP_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/google_cloud-platform.png
!define RABBITMQ_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/rabbitmq.png
!define MONGO_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/mongodb.png
!define NODEJS_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/nodejs.png
!define PYTHON_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/python.png
!define NEXTJS_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/nextjs.png
!define GRAFANA_ICON https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons/grafana.png

skinparam componentStyle uml2
skinparam monochrome true
skinparam nodesep 20
skinparam ranksep 20

cloud "Google Cloud Platform" as gcp {
    node "Kubernetes Cluster (GKE)" as k8s {
        component "Frontend (Next.js)" as frontend {
            icon NEXTJS_ICON
        }

        component "API (Flask)" as api {
            icon PYTHON_ICON
        }

        component "Metrics API (Node.js)" as metrics {
            icon NODEJS_ICON
        }

        database "MongoDB" as mongo {
            icon MONGO_ICON
        }

        queue "RabbitMQ" as rabbitmq {
            icon RABBITMQ_ICON
        }

        component "Ingress (Nginx)" as ingress {
            icon K8S_ICON
        }

        component "cert-manager" as certmanager {
            icon K8S_ICON
        }
    }
}

component "Let's Encrypt" as letsencrypt {
}

component "Positionstack API" as positionstack {
}

component "Grafana" as grafana {
    icon GRAFANA_ICON
}

actor "User" as user

' Connections
user --> ingress : HTTPS
ingress --> frontend : HTTP
ingress --> api : HTTP
frontend --> api : API Calls
api --> mongo : Data Storage
api --> rabbitmq : Publishes Events
metrics --> rabbitmq : Consumes Events
metrics --> mongo : Stores Metrics
metrics --> grafana : Exposes Metrics
certmanager --> letsencrypt : ACME Protocol
api --> positionstack : Geocoding API

@enduml
```